name: Node CI

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '24'

jobs:
  ci:
    name: Test, lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type check
        run: yarn tsc

      - name: Lint
        run: yarn lint:all

      - name: Test
        run: yarn test --watch=false

      - name: Build
        run: yarn build:all
